version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:15.14.0'
    steps:
      - 'checkout'
      - restore_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
      - run: 'yarn install --frozen-lockfile'
      - save_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
          paths:
            - '~/.cache/yarn'
      - run: 'yarn ci'
      - run: 'bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN'
